spring:
  datasource:
    url: jdbc:postgresql://<HOST>:<PORT>/<DB>?sslmode=prefer
    username: <USER>
    password: <PASS>
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

server:
  port: 8081

app:
  jwt:
    secret: "REPLACE_ME_MIN_32_CHARS"
    ttl-minutes: 60
  otp:
    ttl-minutes: 5
