server:
  port: 8082

spring:
  application:
    name: nvr-service

  datasource:
    url: jdbc:postgresql://89.23.102.97:5432/oko_api?sslmode=prefer
    username: oko_user
    password: Mx@:.s7T@#YUrg
  jpa:
    hibernate:
      ddl-auto: update

    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true

# ключ для CryptoService
nvr:
  crypto:
    masterKeyBase64: "yn7vKJJS0NMYuQgUy3PpJPN9ZwevVH0cRZ0eV2H465U="

# JWT настройки (секрет должен совпадать с тем, кто подписывает токены в auth-service)
app:
  jwt:
    secret: "change-me-please-change-me-please-32b+"
  logging:
    level:
      org.springframework.security: DEBUG
      com.nvr.nvrservice.security: DEBUG
